### ISSUE TITLE
gramtools build error

### ISSUE THREAD

**Issue by duzezhen** [iqbal-lab-org/gramtools#166]
When I run gramtools build, the software throws errors. But when I separate the variants by chromosome, the software works fine, I don't know the reason. Thanks a lot if you can help me out.

**This is error:**
> 2022-06-29 17:35:29,252 gramtools    DEBUG    Ran vcf_record_clustering in: 218.30659580230713 seconds
2022-06-29 17:35:29,252 gramtools    INFO     Running build prg from VCF(s) on /home/xxx/analyze/graph/xxx-ho/gramtools/top50/build/build.vcf
[W::vcf_parse] Contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] INFO 'SVTYPE' is not defined in the header, assuming Type=String
[W::vcf_parse] Contig 'chr2' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'chr3' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'chr4' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'chr5' is not defined in the header. (Quick workaround: index the file with tabix.)
2022-06-29 17:51:32,219 gramtools    DEBUG    Ran build prg from VCF(s) in: 1181.2732882499695 seconds
2022-06-29 17:51:32,231 gramtools    INFO     Running backend build
2022-06-29 17:51:32,231 gramtools    DEBUG    Executing command:
/home/xxx/software/miniconda3/envs/gramtools/lib/python3.9/site-packages/gramtools/bin/gram build --gram_dir ./build --ref ../../refgenome.rep.fa --kmer_size 10 --max_threads 10 --all_kmers --debug
2022-06-29 17:51:32,231 gramtools    DEBUG    Using current working directory:
/home/xxx/analyze/graph/xxx-ho/gramtools/top50
2022-06-29 17:56:27,993 gramtools    ERROR    Traceback:
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/gramtools/lib/python3.9/site-packages/gramtools/commands/report.py", line 25, in reportify
    original_result = f(report, action, command_paths, *args)
  File "/home/xxx/miniconda3/envs/gramtools/lib/python3.9/site-packages/gramtools/commands/build/build.py", line 93, in execute_gramtools_cpp_build
    raise Exception(f"while running backend build:\n{command_result.stderr}")
Exception: while running backend build:
**gram: /home/brice/Desktop/main_PhD/git_repos/gramtools/libgramtools/src/prg/coverage_graph.cpp:159: marker_type cov_Graph_Builder::find_marker_type(const uint32_t&): Assertion `pos <= end_pos' failed.**
2022-06-29 17:56:27,993 gramtools    ERROR    Unsuccessful gramtools_build. Process reported to /home/xxx/analyze/graph/xxx-ho/gramtools/top50/build/build_report.json

**Comment by bricoletc** [comment]
Hi @duzezhen , sorry for the late reply. What do you mean by 'separate the variants by chromosome'?
